id: PCF523200
initial_creation_type: input
source_metadata:
  title: 'MSV 6,04: Pañcaka'
  language: bo
  volumes:
    a20ed09fcbc9404c977b53c9472ec0c0:
      title: Pañcaka
      base_file: Pañcaka.txt
      work_id: W0E49BE59
  chapter_to_tile: {}
created_at: '2022-03-01T22:55:01.163882'
last_modified_at: '2022-03-01T22:55:01.163889'
